apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-apps
data:
  RABBITMQ_HOSTNAME: rabbitmq-server.default.svc.cluster.local 
  RABBITMQ_PORT: "5672"
  RABBITMQ_PROTOCOL: "amqp://"
  PG_HOST: postgres-svc.default.svc.cluster.local
  PG_PORT: "5432"
  PG_DB_NAME: "postgresdb"
  REDIS_HOST: redis-server-master.default.svc.cluster.local
  REDIS_PORT: "6379"