apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: full-stack-app
spec:
  project: default 
  source:
    repoURL: "https://github.com/Amouhwilliam/k8s-infra-gitOps"
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy: 
    automated: {}