apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-app
  #minReadySeconds: 5
  #strategy:
  #rollingUpdate:
  #maxSurge: 1
  #maxUnavailable: 0
  #type: RollingUpdate
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
      - name: main-app
        image: william97/devices-app-main_app:latest
        imagePullPolicy: Always
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-apps
              key: main_app_api_url
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 3000
          name: main-app-svc

