apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime-app
  #minReadySeconds: 5
  #strategy:
    #rollingUpdate:
      #maxSurge: 1
      #maxUnavailable: 0
    #type: RollingUpdate
  template:
    metadata:
      labels:
        app: realtime-app
    spec:
      containers:
      - name: realtime-app
        image: william97/devices-app-realtime_app:latest
        imagePullPolicy: Always
        env:
        - name: VITE_WS_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-apps
              key: realtime_app_ws_url
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-apps
              key: realtime_app_api_url
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 5173
          name: rlt-app-svc

