apiVersion: v1
kind: Service
metadata:
  name: main-app-svc
  namespace: default
  labels:
    app: main-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30010
  selector:
    app: main-app
