apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-svc
  namespace: default
  labels:
    app: nodejs-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3333
    targetPort: 3333
    nodePort: 32000
  selector:
    app: nodejs-app
