apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: default
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: postgres-svc
  selector:
    app: postgres
