apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  namespace: default
  labels:
    app: python-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31000
  selector:
    app: python-app