apiVersion: v1
kind: Service
metadata:
  name: rlt-app-svc
  labels:
    app: realtime-app
spec:
  type: NodePort
  ports:
  - port: 5173
    targetPort: rlt-app-svc
    nodePort: 30015
  selector:
    app: realtime-app
