apiVersion: v1
kind: Service
metadata:
  name: redis-stack-svc
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: redis-stack-svc
  selector:
    app: redis-stack
